 - hosts: monitoring
   vars:
     pip_install_packages:
       - name: docker
       - name: docker-compose

   pre_tasks:
     - name: Setup | Install required packages 
       yum: 
          name: "{{ item }}" 
          state: latest 
       loop: 
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          - python2-pip
 
     - name: Setup | Remove epel
       yum:
         name: epel-release
         state: absent

   roles:
     - geerlingguy.docker
     - geerlingguy.pip
